// Auto-generated by tools/update_dashboard_data.py
import type { Article } from './types';

export const mockArticles: Article[] = [
  {
    "id": "1",
    "source": "ai_rundown",
    "title": "Exclusive: Microsoft AI launches Copilot VisionPLUS: Infinite memory, AI companions, AI agents, and moreRowan Cheung, +1",
    "url": "https://www.therundown.ai/p/microsoft-ai-launches-copilot-vision",
    "published_date": "2026-02-14T20:34:56.023336",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/c31e44b2-abbb-41c9-8866-c0e9c570fb11/1_miscrosoft__2_.jpg",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069026",
    "scraped_at": "2026-02-14T20:34:56.023337"
  },
  {
    "id": "2",
    "source": "ai_rundown",
    "title": "Exclusive: Cisco launches AI DefensePLUS: Free event to learn from OpenAI, Scale AI, and moreRowan Cheung, +1",
    "url": "https://www.therundown.ai/p/cisco-announces-ai-defense",
    "published_date": "2026-02-14T20:34:56.023319",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/77950a19-2d30-49da-bb0b-c81bfc121c12/1-cover.jpg",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069031",
    "scraped_at": "2026-02-14T20:34:56.023320"
  },
  {
    "id": "3",
    "source": "ai_rundown",
    "title": "Exclusive: UiPath launches next-gen platform for 'Agentic Automation'PLUS: How agents are transforming the future of workRowan Cheung",
    "url": "https://www.therundown.ai/p/ui-path-launches-agentic-automation-platform",
    "published_date": "2026-02-14T20:34:56.023301",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/f3c8478c-c1d1-43a4-a9c9-181357654930/uipath_cover.jpg",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069034",
    "scraped_at": "2026-02-14T20:34:56.023302"
  },
  {
    "id": "4",
    "source": "ai_rundown",
    "title": "Dropbox redefines the future of work with DashDropbox\u2019s Fall 2025 release brings AI deeper into teams workflowsRowan Cheung",
    "url": "https://www.therundown.ai/p/dropbox-redefines-the-future-of-work-with-dash",
    "published_date": "2026-02-14T20:34:56.023284",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/14108b98-32cf-42ee-9ddc-0a3c56b262f8/Dropbox_cover.png",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069037",
    "scraped_at": "2026-02-14T20:34:56.023285"
  },
  {
    "id": "5",
    "source": "ai_rundown",
    "title": "Exclusive: Microsoft's hybrid AI visionPLUS: Copilot+ PCs, NPUs, agentic AI, and moreRowan Cheung",
    "url": "https://www.therundown.ai/p/microsofts-hybrid-ai-vision",
    "published_date": "2026-02-14T20:34:56.023267",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/baf4ea6d-ee25-4ca7-8f81-a3f868c2b138/NPU_cover.png",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069040",
    "scraped_at": "2026-02-14T20:34:56.023268"
  },
  {
    "id": "6",
    "source": "ai_rundown",
    "title": "Exclusive interview: Inside Meta's AI glasses master planMark Zuckerberg on neural control, superintelligence, and AI coachingRowan Cheung, +2",
    "url": "https://www.therundown.ai/p/inside-metas-ai-glasses-master-plan",
    "published_date": "2026-02-14T20:34:56.023250",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/685ab640-ee4e-49d3-b048-ffbd63c39e37/cover.png",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069042",
    "scraped_at": "2026-02-14T20:34:56.023250"
  },
  {
    "id": "7",
    "source": "ai_rundown",
    "title": "Exclusive: The enterprise AI playbookBring AI to your data anywhere with security, trust, and governance baked inShubham Sharma, +2",
    "url": "https://www.therundown.ai/p/exclusive-the-enterprise-ai-playbook",
    "published_date": "2026-02-14T20:34:56.023232",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/9d254c68-a4f6-4baa-9343-07d6cd70c80e/Cloudera_cover2.png",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069045",
    "scraped_at": "2026-02-14T20:34:56.023233"
  },
  {
    "id": "8",
    "source": "ai_rundown",
    "title": "Exclusive interview: Sam Altman on Dev Day and AI's future PLUS: Google releases Gemini Computer Use for AI browser controlZach Mink, +4",
    "url": "https://www.therundown.ai/p/exclusive-interview-sam-altman-on-dev-day-and-ais-future",
    "published_date": "2026-02-14T20:34:56.023214",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/5468a382-b239-49a7-8d5a-3b2a67eb3bfb/Sam_altman2.png",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069047",
    "scraped_at": "2026-02-14T20:34:56.023215"
  },
  {
    "id": "9",
    "source": "ai_rundown",
    "title": "Sam Altman\u2019s OpenAI succession planPLUS: Build a \"brand twin\" that writes in your exact voiceZach Mink, +4",
    "url": "https://www.therundown.ai/p/sam-altmans-openai-succession-plan",
    "published_date": "2026-02-14T20:34:56.023195",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/050bdd77-5447-4eec-8464-f1ce1e73b39f/1770159130973.png",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069050",
    "scraped_at": "2026-02-14T20:34:56.023196"
  },
  {
    "id": "10",
    "source": "ai_rundown",
    "title": "Anthropic\u2019s ad-free campaign takes aim at OpenAIPLUS: Set up a coordinated coding team with the Codex AppZach Mink, +4",
    "url": "https://www.therundown.ai/p/anthropics-ad-free-campaign-takes-aim-at-openai",
    "published_date": "2026-02-14T20:34:56.023177",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/403cd88c-1513-4ca1-b242-c78c6d31271e/adsclaude.jpg",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069053",
    "scraped_at": "2026-02-14T20:34:56.023178"
  },
  {
    "id": "11",
    "source": "ai_rundown",
    "title": "OpenAI, Anthropic fight on the frontierPLUS: Cut down reporting times with Claude in ExcelZach Mink, +4",
    "url": "https://www.therundown.ai/p/openai-anthropic-fight-on-the-frontier",
    "published_date": "2026-02-14T20:34:56.023159",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/4b43908f-18f5-4f1c-ab32-619ad9ccdcd3/6e29759b50e8b3a8363b38b1f573d854df968671-3840x2160.jpg",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069055",
    "scraped_at": "2026-02-14T20:34:56.023160"
  },
  {
    "id": "12",
    "source": "ai_rundown",
    "title": "AI ads steal the show at Super Bowl LXPLUS: Build custom lead widgets for your site without codingZach Mink, +4",
    "url": "https://www.therundown.ai/p/ai-ads-steal-the-show-at-super-bowl-lx",
    "published_date": "2026-02-14T20:34:56.023139",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/93c6e496-d385-4126-9515-d689ccee1b47/svedka.jpg",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069058",
    "scraped_at": "2026-02-14T20:34:56.023140"
  },
  {
    "id": "13",
    "source": "ai_rundown",
    "title": "ByteDance stuns the AI video worldPLUS: Build an AI-powered sales objection handlerZach Mink, +4",
    "url": "https://www.therundown.ai/p/bytedance-stuns-the-ai-video-world",
    "published_date": "2026-02-14T20:34:56.023121",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/a7027f07-190e-49c6-a0b5-da8d9d55f4a2/seedream20.jpg",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069060",
    "scraped_at": "2026-02-14T20:34:56.023122"
  },
  {
    "id": "14",
    "source": "ai_rundown",
    "title": "xAI's co-founder exodus continuesPLUS: Improve Claude Code with  the \u201cInsights\u201d featureZach Mink, +4",
    "url": "https://www.therundown.ai/p/xai-co-founder-exodus-continues",
    "published_date": "2026-02-14T20:34:56.023102",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/4186664b-5a09-45cf-ae54-96b2576dd720/tonywu.jpg",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069063",
    "scraped_at": "2026-02-14T20:34:56.023103"
  },
  {
    "id": "15",
    "source": "ai_rundown",
    "title": "xAI's next phase unleashedPLUS: Turn SOP docs into talking-head training videosZach Mink, +4",
    "url": "https://www.therundown.ai/p/xai-s-next-phase-unleashed",
    "published_date": "2026-02-14T20:34:56.023082",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/c49cba46-2ead-4e03-b6d9-c06d97e4804a/Upscaled_Image.png",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069065",
    "scraped_at": "2026-02-14T20:34:56.023084"
  },
  {
    "id": "16",
    "source": "ai_rundown",
    "title": "Google's upgrade breaks reasoning barriersPLUS: How to generate a TV commercial with AIZach Mink, +4",
    "url": "https://www.therundown.ai/p/googles-upgrade-breaks-reasoning-barriers",
    "published_date": "2026-02-14T20:34:56.023052",
    "summary": "Read the full article on The Rundown AI.",
    "author": "The Rundown AI",
    "image_url": "https://media.beehiiv.com/cdn-cgi/image/format=auto,fit=scale-down,onerror=redirect/uploads/asset/file/f6c44368-675a-425a-ab3e-1c958303dbac/deepthink.jpg",
    "tags": [
      "AI News"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069068",
    "scraped_at": "2026-02-14T20:34:56.023061"
  },
  {
    "id": "17",
    "source": "reddit",
    "title": "Outside the Saloon - A Frontier Slot Adventure made in 5 hours with AI",
    "url": "https://www.reddit.com/r/singularity/comments/1r4mjga/outside_the_saloon_a_frontier_slot_adventure_made/",
    "published_date": "2026-02-14T20:21:32",
    "summary": "",
    "author": "Sea-Signature-1496",
    "image_url": "https://preview.redd.it/2av8ugiiudjg1.jpeg?auto=webp&s=2f3e8a511ba1ca4be49004ae3d231a52065562ab",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069070",
    "scraped_at": "2026-02-14T20:34:55.637746"
  },
  {
    "id": "18",
    "source": "reddit",
    "title": "[P] I trained YOLOX from scratch to avoid Ultralytics' AGPL (aircraft detection on iOS)",
    "url": "https://www.reddit.com/r/MachineLearning/comments/1r4mcwu/p_i_trained_yolox_from_scratch_to_avoid/",
    "published_date": "2026-02-14T20:13:59",
    "summary": "",
    "author": "MzCWzL",
    "image_url": "https://external-preview.redd.it/VgxN_BHzj3QWKLjM_HicsmE5yLu-TPCy60DlF6DG4rc.jpeg?auto=webp&s=c36554142768e4822d395e2250d4e2417c897c8d",
    "tags": [
      "MachineLearning",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069073",
    "scraped_at": "2026-02-14T20:34:54.753358"
  },
  {
    "id": "19",
    "source": "reddit",
    "title": "Our latest reports on robots | 60 Minutes Full Episodes",
    "url": "https://www.reddit.com/r/singularity/comments/1r4lx22/our_latest_reports_on_robots_60_minutes_full/",
    "published_date": "2026-02-14T19:55:03",
    "summary": "",
    "author": "Worldly_Evidence9113",
    "image_url": "https://external-preview.redd.it/5EyJeBa11NYH2BwaSxB6AWyTeDoMV4ODYiddbPYLDEk.jpeg?auto=webp&s=7774d541a93ab8714b534d69700af9e7a03f8af6",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069075",
    "scraped_at": "2026-02-14T20:34:55.637761"
  },
  {
    "id": "20",
    "source": "reddit",
    "title": "OpenAI: Lockdown Mode and Elevated Risk labels in ChatGPT",
    "url": "https://www.reddit.com/r/singularity/comments/1r4kk1p/openai_lockdown_mode_and_elevated_risk_labels_in/",
    "published_date": "2026-02-14T18:55:00",
    "summary": "",
    "author": "BuildwithVignesh",
    "image_url": null,
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069078",
    "scraped_at": "2026-02-14T20:34:55.637772"
  },
  {
    "id": "21",
    "source": "reddit",
    "title": "GPT-5.2-xHigh &amp; Gemini 3 Pro Based Custom Multi-agentic Deepthink: Pure Scaffolding &amp; Context Manipulation Beats Latest Gemini 3 Deep Think",
    "url": "https://www.reddit.com/r/singularity/comments/1r4k78o/gpt52xhigh_gemini_3_pro_based_custom_multiagentic/",
    "published_date": "2026-02-14T18:37:54",
    "summary": "",
    "author": "Ryoiki-Tokuiten",
    "image_url": "https://preview.redd.it/0gk4dr7tkgjg1.png?width=140&amp;height=76&amp;auto=webp&amp;s=f876f57a0f36a5870ff49d6fc204bcb29dabc8da",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069080",
    "scraped_at": "2026-02-14T20:34:55.637783"
  },
  {
    "id": "22",
    "source": "reddit",
    "title": "Men are from mars, women from Venus - how Claude helps my relationship.",
    "url": "https://www.reddit.com/r/artificial/comments/1r4k4wj/men_are_from_mars_women_from_venus_how_claude/",
    "published_date": "2026-02-14T18:34:45",
    "summary": "Long before AI, I realized that fighting / arguing with  my wife is way more effective over text.\n\nIn the middle of a heated fight I would just tell her \u201clet\u2019s move to text\u201d and go sit on a bench outside near the lake where it\u2019s calm.\n\nThe reason is - when it\u2019s heated face to face, you make poor word choices because you don\u2019t have time to think. So you say all torn things you don\u2019t mean, and it\u2019s compounded by the fact that your partner make their own interpretations based on their trauma, patte...",
    "author": "OptimismNeeded",
    "image_url": null,
    "tags": [
      "artificial",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069083",
    "scraped_at": "2026-02-14T20:34:53.554384"
  },
  {
    "id": "23",
    "source": "reddit",
    "title": "Fran\u00e7ois Chollet favors a slow takeoff scenario (no \"foom\" exponentials)",
    "url": "https://www.reddit.com/r/singularity/comments/1r4jfxq/fran\u00e7ois_chollet_favors_a_slow_takeoff_scenario/",
    "published_date": "2026-02-14T17:59:25",
    "summary": "I kind of disagree with this take, being closer from a Goertzel thinking we'll get a very short time between AGI and ASI (although i'm not certain about AGI nor timelines).\n\nIt feels like Chollet is making a false equivocacy between technological improvement of the past 3 centuries and this one. If we apply this logic, for example, to the timespan between the first hot air balloon (1783), the invention of aviation (1903) and the first man on the Moon (1969), this doesn't fit. It doesn't mean tha...",
    "author": "FomalhautCalliclea",
    "image_url": "https://preview.redd.it/bm0oiec0egjg1.png?auto=webp&s=f09ddc1fc6c5c527ccefe751d4ad77c8b41b2006",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069086",
    "scraped_at": "2026-02-14T20:34:55.637796"
  },
  {
    "id": "24",
    "source": "reddit",
    "title": "Rumored/maybe confirmed? SOTA model - Seed 2.0 Pro - by ByteDance",
    "url": "https://www.reddit.com/r/singularity/comments/1r4j67j/rumoredmaybe_confirmed_sota_model_seed_20_pro_by/",
    "published_date": "2026-02-14T17:44:48",
    "summary": "If this is true, is this a bigger moment than DeepSeek, considering ByteDance is also the creator of the SOTA SeeDance Video model, has all TikTok/domestic TikTok data, and is a huge Tech Company that should be able to compete/maybe even beat the American AI labs over the long term?  \n  \nEdit: Confirmed, courtesy of /u/[Warm-Letter8091](https://www.reddit.com/user/Warm-Letter8091/): post from the actual bytedance staff -\u00a0[https://x.com/quanquangu/status/2022560162406707642?s=46](https://x.com/qu...",
    "author": "acoolrandomusername",
    "image_url": "https://preview.redd.it/hdir13f8cgjg1.jpeg?auto=webp&s=030ddd789cbe0c8d67eec20b2a22fdefe2682c34",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069088",
    "scraped_at": "2026-02-14T20:34:55.637809"
  },
  {
    "id": "25",
    "source": "reddit",
    "title": "Pentagon's use of Claude during Maduro raid sparks Anthropic feud",
    "url": "https://www.reddit.com/r/artificial/comments/1r4hgnu/pentagons_use_of_claude_during_maduro_raid_sparks/",
    "published_date": "2026-02-14T16:05:14",
    "summary": "The U.S. military used Anthropic's [Claude](https://www.axios.com/2026/01/21/google-gemini-ai-chatgpt-claude-openai) AI model during the operation to capture Venezuela's [Nicol\u00e1s Maduro](https://www.axios.com/2026/01/03/maduro-capture-trump-venezuela-operation), two sources with knowledge of the situation told Axios.\n\n\"Anthropic asked whether their software was used for the raid to capture Maduro, which caused real concerns across the Department of War indicating that they might not approve if i...",
    "author": "Naurgul",
    "image_url": "https://external-preview.redd.it/2KXjeG9g2HY28Cq7QZl8DH5VTfj9mcZIkJKLDkmH9M0.jpeg?auto=webp&s=aaf181cbe553cdcc594d82b4fc76c5b8172becee",
    "tags": [
      "artificial",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069091",
    "scraped_at": "2026-02-14T20:34:53.554410"
  },
  {
    "id": "26",
    "source": "reddit",
    "title": "HUSKY: Humanoid Skateboarding System via Physics-Aware Whole-Body Control",
    "url": "https://www.reddit.com/r/singularity/comments/1r4glpd/husky_humanoid_skateboarding_system_via/",
    "published_date": "2026-02-14T15:12:12",
    "summary": "[https://husky-humanoid.github.io/](https://husky-humanoid.github.io/)...",
    "author": "GraceToSentience",
    "image_url": "https://external-preview.redd.it/cm4wMjFvbXVrZmpnMc3KXaKqscumgIAdv5q_F5tx8IE4a71hev6-8f10CG3J.png?format=pjpg&auto=webp&s=909e80e544d940fb6f19e2a684b3b5c648a0c78f",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069093",
    "scraped_at": "2026-02-14T20:34:55.637820"
  },
  {
    "id": "27",
    "source": "reddit",
    "title": "[D] Asymmetric consensus thresholds for multi-annotator NER \u2014 valid approach or methodological smell?",
    "url": "https://www.reddit.com/r/MachineLearning/comments/1r4gjme/d_asymmetric_consensus_thresholds_for/",
    "published_date": "2026-02-14T15:08:29",
    "summary": "## Context\n\nI'm training a Spanish legal NER model (RoBERTa-based, 28 PII categories) using curriculum learning. For the real-world legal corpus (BOE/BORME gazette), I built a multi-annotator pipeline with 5 annotators:\n\n| Annotator | Type | Strengths |\n|-----------|------|-----------|\n| RoBERTa-v2 | Transformer (fine-tuned) | PERSON, ORG, LOC |\n| Flair | Transformer (off-the-shelf) | PERSON, ORG, LOC |\n| GLiNER | Zero-shot NER | DATE, ADDRESS, broad coverage |\n| Gazetteer | Dictionary lookup | ...",
    "author": "AlexAlves87",
    "image_url": "https://preview.redd.it/aukkp6r9kfjg1.png?auto=webp&s=adabddced82299d44151529c905e66a759eb5533",
    "tags": [
      "MachineLearning",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069096",
    "scraped_at": "2026-02-14T20:34:54.753372"
  },
  {
    "id": "28",
    "source": "reddit",
    "title": "[D] ARR Jan ARR Discussion",
    "url": "https://www.reddit.com/r/MachineLearning/comments/1r4fotm/d_arr_jan_arr_discussion/",
    "published_date": "2026-02-14T14:14:59",
    "summary": "It will be released in one day, so created this. \n\n...",
    "author": "Striking-Warning9533",
    "image_url": null,
    "tags": [
      "MachineLearning",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069100",
    "scraped_at": "2026-02-14T20:34:54.753381"
  },
  {
    "id": "29",
    "source": "reddit",
    "title": "[D] Interesting Gradient Norm Goes Down-Up-Down",
    "url": "https://www.reddit.com/r/MachineLearning/comments/1r4bbbd/d_interesting_gradient_norm_goes_downupdown/",
    "published_date": "2026-02-14T10:09:31",
    "summary": "When I'm training an MoE model with modelscope-swift (with megatron as the backend), I find the gradient norm goes up and down during the training phase. Although the language modeling loss continually goes down, I want to figure out **why** the training process would behave like this. Is it a problem, and **how** to resolve this issue?\n\nSome details:\n\n* init: norm with std=0.02\n* lr: warmup 2.5k steps and constant to 4e-4, bsz: 4M tokens\n* setting: pre-training from scratch\n* model: a smaller Q...",
    "author": "Spico197",
    "image_url": "https://preview.redd.it/hg2fed5u2ejg1.png?width=140&amp;height=121&amp;auto=webp&amp;s=c61e1c948658db8d5b030e0293726d132eddbee5",
    "tags": [
      "MachineLearning",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069102",
    "scraped_at": "2026-02-14T20:34:54.753389"
  },
  {
    "id": "30",
    "source": "reddit",
    "title": "OpenAI Says Internal Model May Have Solved 6 Frontier Research Problems.",
    "url": "https://www.reddit.com/r/singularity/comments/1r4akax/openai_says_internal_model_may_have_solved_6/",
    "published_date": "2026-02-14T09:31:25",
    "summary": "",
    "author": "NutInBobby",
    "image_url": "https://preview.redd.it/8zybl0i0wdjg1.png?auto=webp&s=69bde85b4c97c81f177eddd6842b26cfd0ec2ee9",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069105",
    "scraped_at": "2026-02-14T20:34:55.637831"
  },
  {
    "id": "31",
    "source": "reddit",
    "title": "It's already here.",
    "url": "https://www.reddit.com/r/singularity/comments/1r48leh/its_already_here/",
    "published_date": "2026-02-14T07:57:06",
    "summary": "",
    "author": "KreekisaL_1234",
    "image_url": "https://preview.redd.it/9jeb7xg8fdjg1.png?auto=webp&s=086d3ea2a1cd5b8ffb257388043f5a28a65158c2",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069107",
    "scraped_at": "2026-02-14T20:34:55.637841"
  },
  {
    "id": "32",
    "source": "reddit",
    "title": "[D] Minimax 2.5 is out, considering local deployment",
    "url": "https://www.reddit.com/r/MachineLearning/comments/1r48dvk/d_minimax_25_is_out_considering_local_deployment/",
    "published_date": "2026-02-14T07:47:32",
    "summary": "I recently tried out Minimax 2.5, which just dropped, and from what I\u2019ve heard, the results are pretty impressive. I gave it a go on zenmux, and I have to say, it really covers a lot of ground. The flexibility, speed, and accuracy are definitely noticeable improvements.\n\n\n\nNow, I\u2019m thinking about deploying it locally. I\u2019ve used Ollama for deployments before, but I noticed that for Minimax 2.5, Ollama only offers a cloud version. I\u2019m curious about other deployment options and wondering what the d...",
    "author": "Dramatic_Spirit_8436",
    "image_url": null,
    "tags": [
      "MachineLearning",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069110",
    "scraped_at": "2026-02-14T20:34:54.753396"
  },
  {
    "id": "33",
    "source": "reddit",
    "title": "[R] Lrec 26 acceptance emails",
    "url": "https://www.reddit.com/r/MachineLearning/comments/1r47czy/r_lrec_26_acceptance_emails/",
    "published_date": "2026-02-14T06:59:38",
    "summary": "submitted a paper there but no emails yet should I wait till tmrw?...",
    "author": "ChestFree776",
    "image_url": null,
    "tags": [
      "MachineLearning",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069112",
    "scraped_at": "2026-02-14T20:34:54.753402"
  },
  {
    "id": "34",
    "source": "reddit",
    "title": "Priorities",
    "url": "https://www.reddit.com/r/singularity/comments/1r476vu/priorities/",
    "published_date": "2026-02-14T06:51:38",
    "summary": "Credit: [Charles Curran on X (Seedance 2.0)](https://x.com/charliebcurran/status/2022463429823598999)...",
    "author": "Outside-Iron-8242",
    "image_url": "https://external-preview.redd.it/ajQ2cGM5OXEyZGpnMVTbP7qoCZJKtQixVdxlaRoZ8eohdXK04VnkaDMukyv3.png?format=pjpg&auto=webp&s=66c9bb932201f4f891eb91d26122ba251b0113a8",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069115",
    "scraped_at": "2026-02-14T20:34:55.637852"
  },
  {
    "id": "35",
    "source": "reddit",
    "title": "Remote Labor Index - A new benchmark for AI replacing real workers",
    "url": "https://www.reddit.com/r/singularity/comments/1r46mao/remote_labor_index_a_new_benchmark_for_ai/",
    "published_date": "2026-02-14T06:25:19",
    "summary": "",
    "author": "FreshBlinkOnReddit",
    "image_url": null,
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069117",
    "scraped_at": "2026-02-14T20:34:55.637862"
  },
  {
    "id": "36",
    "source": "reddit",
    "title": "[D] Struggling on the NLP job market as a final-year PhD , looking for advice",
    "url": "https://www.reddit.com/r/MachineLearning/comments/1r467ra/d_struggling_on_the_nlp_job_market_as_a_finalyear/",
    "published_date": "2026-02-14T06:06:53",
    "summary": "I\u2019m a final-year PhD student in the U.S. working primarily on NLP. I\u2019ve been on the job market this year (since October), and I\u2019m trying to understand where I might be going wrong.\n\nMy priority was academia, but after submitting 30 tenure-track applications, I\u2019ve heard nothing but crickets.\n\nI also applied for industry roles:  \n\\~200 applications \u2192 8 interviews, no offers.\n\n**My research profile:**  \n17 peer-reviewed papers and 1 pre-print, \\~13 first-author, about 8 in A/A\\* ACLvenues (rest are...",
    "author": "RepresentativeBed838",
    "image_url": null,
    "tags": [
      "MachineLearning",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069120",
    "scraped_at": "2026-02-14T20:34:54.753409"
  },
  {
    "id": "37",
    "source": "reddit",
    "title": "Pyro\u2019s Required Reading: An Overview of 20 Papers Anyone Will Understand",
    "url": "https://www.reddit.com/r/singularity/comments/1r466uq/pyros_required_reading_an_overview_of_20_papers/",
    "published_date": "2026-02-14T06:05:45",
    "summary": "Over the next few weeks, I will take a closer look at different topics in AI/ML research and try to explain the key papers on each topic in a way that even your mom will understand.\n\nCheers...",
    "author": "Pyros-SD-Models",
    "image_url": "https://external-preview.redd.it/KrQsAi2aYnNC39gSGx3IaLPCee6zxUrVilY2uA11UXU.jpeg?auto=webp&s=f4c0b59188ee7967b006811560d60f57345e13a9",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069122",
    "scraped_at": "2026-02-14T20:34:55.637874"
  },
  {
    "id": "38",
    "source": "reddit",
    "title": "Pentagon Used Anthropic\u2019s Claude in Maduro Venezuela Raid",
    "url": "https://www.reddit.com/r/singularity/comments/1r440pt/pentagon_used_anthropics_claude_in_maduro/",
    "published_date": "2026-02-14T04:32:11",
    "summary": "\u201dWe cannot comment on whether Claude, or any other AI model, was used for any specific operation, classified or otherwise,\u201d said an Anthropic spokesman. \u201cAny use of Claude\u2014whether in the private sector or across government\u2014is required to comply with our Usage Policies, which govern how Claude can be deployed. We work closely with our partners to ensure compliance.\u201d\n\n  \nI wonder if their usage policies allow killing people if you're the government?...",
    "author": "Just_Stretch5492",
    "image_url": "https://external-preview.redd.it/RP9EPyZbAnXFDdB_fuqFLmYe7A821t4e6h_wTWJ77CU.jpeg?auto=webp&s=08e15be043f96ed5080dd4c8a297b070860870bf",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069125",
    "scraped_at": "2026-02-14T20:34:55.637887"
  },
  {
    "id": "39",
    "source": "reddit",
    "title": "xAI all hands (after losing 25 senior staff last week, 46 minutes)",
    "url": "https://www.reddit.com/r/singularity/comments/1r43ggm/xai_all_hands_after_losing_25_senior_staff_last/",
    "published_date": "2026-02-14T04:08:08",
    "summary": "",
    "author": "Competitive_Travel16",
    "image_url": "https://external-preview.redd.it/nGj2P11BolGCEnIamE3SRv1BPKxGlyIi66APrWsouqE.jpeg?auto=webp&s=1e9520bb8e48d5963016f64f4e586d553cfe6f58",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069127",
    "scraped_at": "2026-02-14T20:34:55.637897"
  },
  {
    "id": "40",
    "source": "reddit",
    "title": "[D] Benchmarking Deep RL Stability Capable of Running on Edge Devices",
    "url": "https://www.reddit.com/r/MachineLearning/comments/1r41k5r/d_benchmarking_deep_rl_stability_capable_of/",
    "published_date": "2026-02-14T02:52:02",
    "summary": "This post details my exploration for a \"stable stack\" for streaming deep RL (ObGD, SparseInit, LayerNorm, and online normalization) using 433,000 observations of real, non-stationary SSH attack traffic.\n\n**Learnings From Tests:**\n\n* **Computational Efficiency:** Using JAX's AOT compilation pipeline and `cost_analysis()`, the tests measure the per-update FLOP counts. An MLP with two hidden layers of 128 nodes each learner requires 271k FLOPs per update, capable of processing 477k observations/sec...",
    "author": "debian_grey_beard",
    "image_url": "https://external-preview.redd.it/wqE0ohoos7bGLeQAT3ouPj_2aRn-1wKsqpJSzuzY86A.png?auto=webp&s=dd32f6ce0d034af09f8dabf7829f266dd81c1795",
    "tags": [
      "MachineLearning",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069130",
    "scraped_at": "2026-02-14T20:34:54.753417"
  },
  {
    "id": "41",
    "source": "reddit",
    "title": "LLaDA2.1 (100B/16B) released \u2014 now with token editing for massive speed gains",
    "url": "https://www.reddit.com/r/singularity/comments/1r40h9a/llada21_100b16b_released_now_with_token_editing/",
    "published_date": "2026-02-14T02:09:33",
    "summary": "",
    "author": "FeelingWatercress871",
    "image_url": "https://external-preview.redd.it/82mCsHP2SIMtQkvDhPErINi3uSkeLyzxZS6d7hE1-9Y.png?auto=webp&s=2ada4559605b14d05f887cf0ddfba7e9fbf19860",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069132",
    "scraped_at": "2026-02-14T20:34:55.637906"
  },
  {
    "id": "42",
    "source": "reddit",
    "title": "Introducing Open Book Medical AI: Deterministic Knowledge Graph + Compact LLM",
    "url": "https://www.reddit.com/r/artificial/comments/1r3yw21/introducing_open_book_medical_ai_deterministic/",
    "published_date": "2026-02-14T01:09:12",
    "summary": "Introducing Open Book Medical AI: Deterministic Knowledge Graph + Compact LLM\n\nMost medical AI systems today rely heavily on large, opaque language models. They are powerful, but probabilistic, difficult to audit, and expensive to deploy.\n\nWe\u2019ve taken a different approach.\n\nOur medical AI is a hybrid system combining:\n\n\u2022 A compact \\~3GB language model\n\n\u2022 A deterministic proprietary medical Knowledge Graph (5K nodes, 25K edges)\n\n\u2022 A structured RAG-based answer audit layer\n\nThe Knowledge Graph spa...",
    "author": "vagobond45",
    "image_url": "https://external-preview.redd.it/Tw-1IGEyiPk1jIYoVu_Pr5_fcCoquBCKY0Nm8O36V3Q.png?auto=webp&s=62b9b37707cd95cbd40df766a01efc4216909025",
    "tags": [
      "artificial",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069135",
    "scraped_at": "2026-02-14T20:34:53.554423"
  },
  {
    "id": "43",
    "source": "reddit",
    "title": "GPT5.2 Pro derived a new result in theoretical physics",
    "url": "https://www.reddit.com/r/singularity/comments/1r3yi6e/gpt52_pro_derived_a_new_result_in_theoretical/",
    "published_date": "2026-02-14T00:54:31",
    "summary": "Link to tweet: https://x.com/kevinweil/status/2022388305434939693?s=20\n\nLink to paper: https://arxiv.org/pdf/2602.12176\n\nLink to blog: https://openai.com/index/new-result-theoretical-physics/...",
    "author": "socoolandawesome",
    "image_url": "https://preview.redd.it/8basg4mzbbjg1.jpg?width=140&amp;height=140&amp;crop=1:1,smart&amp;auto=webp&amp;s=da79578978d19974458c5aaed41c5aa0e79293fe",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069137",
    "scraped_at": "2026-02-14T20:34:55.637917"
  },
  {
    "id": "44",
    "source": "reddit",
    "title": "Dario Amodei \u2014 \u201cWe are near the end of the exponential\u201d",
    "url": "https://www.reddit.com/r/singularity/comments/1r3wysl/dario_amodei_we_are_near_the_end_of_the/",
    "published_date": "2026-02-13T23:57:13",
    "summary": "",
    "author": "Mindrust",
    "image_url": "https://external-preview.redd.it/hg3Jci_jqsW43Gyos5gzyZxpfd9C8apL_x5ioWgoL0Q.jpeg?auto=webp&s=22f9f66f722ecb259f1c1534588cae0613b9788c",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069140",
    "scraped_at": "2026-02-14T20:34:55.637927"
  },
  {
    "id": "45",
    "source": "reddit",
    "title": "[R] Higher effort settings reduce deep research accuracy for GPT-5 and Gemini Flash 3",
    "url": "https://www.reddit.com/r/MachineLearning/comments/1r3w853/r_higher_effort_settings_reduce_deep_research/",
    "published_date": "2026-02-13T23:30:15",
    "summary": "We evaluated 22 model configurations across different effort/thinking levels on Deep Research Bench (169 web research tasks, human-verified answers). For two of the most capable models, higher effort settings scored worse.  \n  \nGPT-5 at low effort scored 0.496 on DRB. At high effort, it dropped to 0.481, and cost 55% more per query ($0.25 \u2192 $0.39). Gemini 3 Flash showed a 5-point drop going from 0.504 at low effort, to 0.479 at high effort.  \n  \nMost models cluster well under a dollar per task, ...",
    "author": "ddp26",
    "image_url": "https://external-preview.redd.it/PAfzP8_fjhuX4IJFbJ4Ak963wflG-EdScFlAWJCsnpA.png?auto=webp&s=1f8c2b277cda50ddecd2ab8438af75ce6c7ce7d1",
    "tags": [
      "MachineLearning",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069142",
    "scraped_at": "2026-02-14T20:34:54.753425"
  },
  {
    "id": "46",
    "source": "reddit",
    "title": "[P] SoproTTS v1.5: A 135M zero-shot voice cloning TTS model trained for ~$100 on 1 GPU, running ~20\u00d7 real-time on the CPU",
    "url": "https://www.reddit.com/r/MachineLearning/comments/1r3ul8s/p_soprotts_v15_a_135m_zeroshot_voice_cloning_tts/",
    "published_date": "2026-02-13T22:29:26",
    "summary": "I released a new version of my side project: SoproTTS\n\nA 135M parameter TTS model trained for \\~$100 on 1 GPU, running \\~20\u00d7 real-time on a base MacBook M3 CPU.\n\nv1.5 highlights (on CPU):\n\n\u2022 250 ms TTFA streaming latency  \n\u2022 0.05 RTF (\\~20\u00d7 real-time)  \n\u2022 Zero-shot voice cloning  \n\u2022 Smaller, faster, more stable\n\nStill not perfect (OOD voices can be tricky, and there are still some artifacts), but a decent upgrade. Training code TBA.\n\nRepo (demo inside):\u00a0[https://github.com/samuel-vitorino/sopro]...",
    "author": "SammyDaBeast",
    "image_url": "https://external-preview.redd.it/9mtKXNVthZuNnxQnJ7fWe87INdTTdgLsOm_BU2s_REg.png?auto=webp&s=36753d3efbf97901e7d295acc1f7e33fca567c79",
    "tags": [
      "MachineLearning",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069145",
    "scraped_at": "2026-02-14T20:34:54.753432"
  },
  {
    "id": "47",
    "source": "reddit",
    "title": "Figure teases improved finger dexterity",
    "url": "https://www.reddit.com/r/singularity/comments/1r3ukaz/figure_teases_improved_finger_dexterity/",
    "published_date": "2026-02-13T22:28:22",
    "summary": "",
    "author": "Glittering-Neck-2505",
    "image_url": "https://external-preview.redd.it/MzBnb2NndnRsYWpnMSEfVGj4vmc8OKDq0tEdZpsBMstcV0pdqRuPzvbCWIME.png?format=pjpg&auto=webp&s=3f5dc24ee6e1d02024ab3d2bd6c77b65089f2192",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069147",
    "scraped_at": "2026-02-14T20:34:55.637937"
  },
  {
    "id": "48",
    "source": "reddit",
    "title": "[D] How do your control video resolution and fps for a R(2+1)D model?",
    "url": "https://www.reddit.com/r/MachineLearning/comments/1r3tn73/d_how_do_your_control_video_resolution_and_fps/",
    "published_date": "2026-02-13T21:53:57",
    "summary": "So I am using a R(2+1)D with kinetics 400 weights to train a classifier on two sets of videos. The problem is that one of the two classes has all videos of the same resolution and fps, forcing the model to learn those features instead of actually learning pixel changes over time, like R(2+1)D is supposed to.  \nOn the other class, there is diversity and equivalent representation across resolutions, which makes the model totally unusable without any preprocessing.\n\nI have tried preprocessing by re...",
    "author": "BatBoy117",
    "image_url": null,
    "tags": [
      "MachineLearning",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069150",
    "scraped_at": "2026-02-14T20:34:54.753438"
  },
  {
    "id": "49",
    "source": "reddit",
    "title": "ChatGPT 4o is being retired today, and some users are very unhappy about it. A petition with around 20,000 signatures is urging OpenAI not to remove it. The same group is also calling for a mass cancellation of subscriptions in protest.",
    "url": "https://www.reddit.com/r/singularity/comments/1r3saix/chatgpt_4o_is_being_retired_today_and_some_users/",
    "published_date": "2026-02-13T21:04:10",
    "summary": "",
    "author": "likeastar20",
    "image_url": "https://preview.redd.it/2pk00s2w6ajg1.jpg?width=140&amp;height=127&amp;auto=webp&amp;s=e0e9fb04b4346b26c346533443b6c0de9123a68e",
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069152",
    "scraped_at": "2026-02-14T20:34:55.637947"
  },
  {
    "id": "50",
    "source": "reddit",
    "title": "Governor Healey Announces Massachusetts to Become First State to Deploy ChatGPT Across Executive Branch",
    "url": "https://www.reddit.com/r/singularity/comments/1r3sab8/governor_healey_announces_massachusetts_to_become/",
    "published_date": "2026-02-13T21:03:57",
    "summary": "",
    "author": "MountainAlive",
    "image_url": null,
    "tags": [
      "singularity",
      "reddit"
    ],
    "is_saved": false,
    "created_at": "2026-02-14T20:34:56.069155",
    "scraped_at": "2026-02-14T20:34:55.637956"
  }
];
