import json
import glob
import os
from datetime import datetime

def generate_ts_mock_data():
    articles = []
    
    # Read all JSON files in data/
    # Sort files by name to ensure consistent order if multiple exist
    files = sorted(glob.glob('data/*.json'))
    
    print(f"Found {len(files)} data files: {files}")
    
    for f_path in files:
        with open(f_path, 'r') as f:
            try:
                data = json.load(f)
                if isinstance(data, list):
                    articles.extend(data)
            except Exception as e:
                print(f"Error reading {f_path}: {e}")

    # Sort by date (newest first)
    if not articles:
        print("No articles found in data/*.json")
        return

    # Sort by published_date descending
    # Ensure date string parsing works
    articles.sort(key=lambda x: x.get('published_date', ''), reverse=True)
    
    # Limit to top 50
    articles = articles[:50]
    
    # Transform to match Dashboard Article interface
    final_articles = []
    for i, a in enumerate(articles):
        # Default fallback values
        final_articles.append({
            "id": str(i + 1),
            "source": a.get("source", "unknown"),
            "title": a.get("title", "Untitled"),
            "url": a.get("url", "#"),
            "published_date": a.get("published_date", datetime.now().isoformat()),
            "summary": a.get("summary", ""),
            "author": a.get("author", "Unknown"),
            "image_url": a.get("image_url"),
            "tags": a.get("tags", []),
            "is_saved": False,
            "created_at": datetime.now().isoformat(),
            "scraped_at": a.get("scraped_at", datetime.now().isoformat()),
        })

    # Generate TS content
    # Use json.dumps to handle escaping correctly
    json_str = json.dumps(final_articles, indent=2)
    
    ts_content = f"""// Auto-generated by tools/update_dashboard_data.py
import type {{ Article }} from './types';

export const mockArticles: Article[] = {json_str};
"""
    
    with open('dashboard/src/mockData.ts', 'w') as f:
        f.write(ts_content)
        
    print(f"Successfully updated dashboard/src/mockData.ts with {len(final_articles)} real articles.")

if __name__ == "__main__":
    generate_ts_mock_data()
